spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/Jason-zf/spring-cloud-config-server.git
          search-paths: micro-service
          timeout: 60
          skipSslValidation: true
          uri: https://github.com/Jason-zf/config-server.git
server:
  port: 8888