spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/db_todo?createDatabaseIfNotExist=true
    username: root
    password: password

jpa:
  show-sql: true

server:
  port: 8080